version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_NAME=To-Do List
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Vaghela@1999
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - JWT_SECRET=thisissecret
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vaghela@1999
      POSTGRES_DB: "To-Do List"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: